INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (1,0,'Madame Maxime ',1);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (2,1,'Severus Snape',1);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (3,0,'Albus Dumbledore',1);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (4,0,'Rubeus Hagrid',1);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (5,0,'Gryffindor',2);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (6,1,'Hufflepuff',2);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (7,0,'Ravenclaw',2);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (8,0,'Slytherin',2);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (9,0,'H.P. y la piedra filosofal',3);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (10,0,'H.P. y el misterio del príncipe',3);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (11,1,'H.P. y el caliz de fuego',3);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (12,0,'H.P. y el prisionero de azkaban',3);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (13,0,'1',4);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (14,0,'3',4);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (15,1,'7',4);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (16,0,'4',4);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (17,0,'Su lechuza',5);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (18,1,'Hagrid',5);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (19,0,'Albus Dumbledore',5);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (20,0,'Su padre',5);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (21,0,'Kappa',6);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (22,0,'Directioners',6);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (23,1,'Muggles',6);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (24,0,'Humanos',6);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (25,0,'Albus Dumbledore',7);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (26,1,'Minerva McGonagall',7);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (27,0,'Rubeus Hagrid',7);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (28,0,'Tom Riddle',7);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (29,0,'Hermione Granger',8);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (30,0,'Harry Potter',8);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (31,0,'Draco Malfoy',8);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (32,1,'Neville Lombottom',8);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (33,0,'Desmaius',9);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (34,0,'Occulus Reparo',9);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (35,0,'Alohomora',9);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (36,1,'Expecto Patronum',9);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (37,1,'Recuperar algo valioso del lago de Hogwarts',10);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (38,0,'Salir de un laberinto en el bosque perdido',10);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (39,0,'Limpiar las mazmorras ',10);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (40,0,'Escapar de Azkaban',10);

INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (41,0,'Nute',11);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (42,1,'Watto',11);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (43,0,'Sebulba',11);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (44,0,'Wald',11);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (45,0,'Mandalore',12);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (46,1,'Naboo',12);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (47,0,'Takodana',12);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (48,0,'Yavin 4',12);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (49,1,'Conde Dooku',13);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (50,0,'Yoda',13);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (51,0,'Mace Windu',13);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (52,0,'Palpatine',13);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (53,0,'Darth Maul',14);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (54,1,'Darth Sidious',14);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (55,0,'Darth Vader',14);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (56,0,'Darth Tyranus',14);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (57,0,'Boba Fett',15);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (58,0,'Hondo Ohnaka',15);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (59,0,'Mace Windu',15);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (60,1,'Jango Fett',15);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (61,1,'D’Qar',16);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (62,0,'Takodana',16);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (63,0,'Jakku',16);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (64,0,'Endor',16);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (65,0,'Han Solo',17);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (66,1,'Finn',17);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (67,0,'Rey',17);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (68,0,'Poe',17);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (69,0,'FN-36',18);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (70,0,'FN-2018',18);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (71,0,'FN-3881',18);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (72,1,'FN-2187',18);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (73,0,'Gestión de armas',19);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (74,1,'Saneamiento',19);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (75,0,'Lavandería',19);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (76,0,'Mecánica',19);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (77,0,'Los patios de chatarra de Jakku',20);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (78,0,'El Halcón Milenario',20);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (79,0,'La Cantina',20);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (80,1,'El castillo de Maz Kanata',20);

INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (81,0,'SUSAN',21);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (82,0,'LUCY',21);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (83,0,'PETER ',21);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (84,0,'EDMUN',21);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (85,0,'ASTRAN',22);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (86,0,'ASRAN',22);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (87,0,'ASLAN ',22);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (88,0,'ASKAN',22);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (89,0,'CHOCOLATINAS',23);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (90,0,'PASTELITOS DE ALMENDRA',23);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (91,0,'DELICIAS TURCAS',23);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (92,0,'GOFRES',23);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (93,0,'POR LA PUERTA DEL SERVICIO',24);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (94,0,'POR UNA CUEVA',24);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (95,0,'POR UN ARMARIO',24);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (96,0,'POR UNA BAÑERA',24);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (97,0,'1',25);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (98,0,'3',25);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (99,0,'5',25);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (100,0,'6',25);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (101,0,'TUNNUS',26);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (102,0,'LUCNUS',26);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (103,0,'BULTUS',26);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (104,0,'ZURNUS',26);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (105,0,'CASPIAN',27);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (106,0,'MACALIAN',27);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (107,0,'CALIAN',27);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (108,0,'FERNANDITO',27);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (109,0,'C. LEWIS',28);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (110,0,'ARTURO PEREZ REVERTE',28);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (111,0,'JUAN  MANUEL DE PRADA',28);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (112,0,'BENITO PEREZ GALDOS',28);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (113,0,'POR UN SILLON',29);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (114,0,'POR UNA MESA',29);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (115,0,'POR UN CUADRO',29);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (116,0,'POR EL FRIGORIFICO',29);

INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (117,0,'ESPADA',30);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (118,0,'PUÑAL',30);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (119,0,'PISTOLA ',30);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (120,0,'ARCO CON FLECHAS',30);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (121,0,'UN HOBBIT',31);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (122,0,'UN PERRO',31);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (123,0,'UN ORCO',31);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (124,0,'UN HADA',31);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (125,0,'GANDALF',32);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (126,0,'ESTRUJEN',32);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (127,0,'SARUMAN',32);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (128,0,'KINTERIUM',32);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (129,0,'FRODO',33);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (130,0,'SAM SAGAZ',33);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (131,0,'ARAGON',33);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (132,0,'EL REY ENANO',33);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (133,0,'BILBO BOLSON',34);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (134,0,'BARBO BOLSON',34);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (135,0,'BERIO BOLSON',34);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (136,0,'BASTION BOLSON',34);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (137,0,'MAURON',35);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (138,0,'SAURON',35);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (139,0,'TRAURON',35);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (140,0,'CRAURON',35);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (141,0,'MARDOR',36);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (142,0,'MUERDOR',36);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (143,0,'MORDOR ',36);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (144,0,'MENDOR',36);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (145,0,'J.R. LEWIS',37);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (146,0,'J.R.R. TOLKIEN',37);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (147,0,'J.R.R. PEET',37);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (148,0,'J.R.R. POE',37);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (149,0,'LAS TRES TORRES',38);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (150,0,'LAS CUATRO TORRES',38);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (151,0,'LAS DOS TORRES ',38);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (152,0,'LAS CINCO TORRES',38);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (153,0,'EL ASCENSO DEL CABALLERO',39);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (154,0,'EL RETORNO DEL REY',39);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (155,0,'LA CAIDA DEL VILLANO',39);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (156,0,'EL FIN DE LA MALDAD',39);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (157,0,'LA COMUNIDAD DEL ANILLO',40);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (158,0,'LA SOCIEDAD SECRETA DEL ANILLO',40);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (159,0,'EL CLUB DEL ANILLO',40);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (160,0,'LOS INVENCIBLES PORTADORES DEL ANILLO',40);

INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (161,0,'2005',41);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (162,1,'2008',41);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (163,0,'2010',41);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (164,0,'2012',41);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (165,0,'Vanir',42);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (166,1,'Mjolnir',42);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (167,0,'Aesir',42);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (168,0,'Norn',42);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (169,0,'Que quiere estudiar The Hulk',43);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (170,0,'Que él sabe sobre SHIELD',43);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (171,1,'Que están formando un equipo',43);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (172,0,'Que Thaddeus le debe dinero',43);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (173,0,'Adamantium',44);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (174,1,'Vibranio',44);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (175,0,'prometeo',44);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (176,0,'Carbonadio',44);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (177,1,'Gatos',45);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (178,0,'Patos',45);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (179,0,'Reptiles',45);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (180,0,'Mapaches',45);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (181,0,'HOMERO',46);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (182,1,'JARVIS',46);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (183,0,'ALFREDO',46);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (184,0,'MARVIN',46);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (185,1,'T Challa',47);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (186,0,'M Baku',47);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (187,0,'N Jadaka',47);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (188,0,'N Jobu',47);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (189,1,'El chitauri',48);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (190,0,'Los skrulls',48);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (191,0,'El kree',48);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (192,0,'Los flerkens',48);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (193,0,'Thor',49);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (194,1,'Loki',49);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (195,0,'El coleccionista',49);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (196,0,'Tony Stark',49);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (197,1,'Natalie Rushman',50);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (198,0,'Natalia Romanoff',50);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (199,0,'Nicole Rohan',50);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (200,0,'Naya Rabe',50);

INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (201,1,'1923',51);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (202,0,'1945',51);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (203,0,'1970',51);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (204,0,'1911',51);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (205,1,'6',52);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (206,0,'10',52);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (207,0,'12',52);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (208,0,'15',52);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (209,0,'Los Angeles, California',53);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (210,1,'Burbank, California',53);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (211,0,'Jacksonville, Florida',53);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (212,0,'Manhattan, Nueva York',53);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (213,0,'15',54);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (214,0,'8',54);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (215,0,'17',54);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (216,1,'13',54);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (217,0,'Pinocho',55);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (218,0,'Cenicienta',55);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (219,1,'Blancanieves y los siete enanitos',55);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (220,0,'Dumbo',55);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (221,0,'Vaca clarabelle',56);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (222,0,'Pato Donald',56);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (223,1,'Pete',56);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (224,0,'Horacio Horsecollar',56);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (225,0,'Zazu',57);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (226,1,'Iago',57);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (227,0,'Rajah',57);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (228,0,'Gus',57);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (229,0,'Kiara y Mike',58);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (230,0,'Kira y Mac',58);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (231,0,'Keri y Malek',58);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (232,1,'Kida y Milo',58);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (233,1,'Anastasia y Drizella',59);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (234,0,'Anna y Elsa',59);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (235,0,'Jane y melanie',59);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (236,0,'Aurora y Rapunzel',59);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (237,0,'Para rascarse',60);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (238,0,'Un palillo de dientes',60);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (239,1,'Un peine',60);
INSERT INTO `preguntas_opciones` (`id`,`correcta`,`opcion`,`pregunta_id`) VALUES (240,0,'Algo para comer',60);